# Generated by Django 4.2.11 on 2026-03-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cashbook", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashbookentry",
            name="settlement_date",
            field=models.DateField(
                blank=True,
                help_text="Actual settlement date — set when a receivable/payable is marked as done.",
                null=True,
            ),
        ),
    ]
