# Generated by Django 4.2.11 on 2026-03-07 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("business", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeBase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("accounting_standards", "Accounting Standards"),
                            ("auditing_assurance", "Auditing & Assurance Standards"),
                            ("corporate_laws", "Corporate Laws & Governance"),
                            ("direct_taxes", "Direct Taxes"),
                            ("gst_indirect_taxes", "GST & Indirect Taxes"),
                            (
                                "expert_advisory",
                                "Expert Advisory & Professional Guidance",
                            ),
                            ("members_student_services", "Members & Student Services"),
                            (
                                "sustainability_reporting",
                                "Sustainability Reporting Standards",
                            ),
                            ("acts_regulations", "Acts & Regulations"),
                            (
                                "internal_audit",
                                "Internal Audit & Management Accounting",
                            ),
                            ("digital_accounting", "Digital Accounting & Assurance"),
                            ("ethical_standards", "Ethical Standards"),
                            (
                                "financial_reporting_review",
                                "Financial Reporting Review",
                            ),
                            ("insolvency_valuation", "Insolvency & Valuation"),
                            ("peer_review", "Peer Review"),
                            ("icai_journal", "ICAI e-Journal Knowledge"),
                            ("business_data", "Business Data Query"),
                            ("general", "General"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                (
                    "keywords",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Keywords for matching user queries",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Source reference e.g. ICAI Circular, IND-AS 116",
                        max_length=255,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Knowledge Base Entry",
                "verbose_name_plural": "Knowledge Base Entries",
                "db_table": "chatbot_knowledge_base",
                "ordering": ["domain", "question"],
            },
        ),
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Auto-generated from first message",
                        max_length=255,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_sessions",
                        to="business.business",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Session",
                "verbose_name_plural": "Chat Sessions",
                "db_table": "chat_sessions",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("system", "System"),
                        ],
                        max_length=10,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "intent",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("knowledge_query", "Knowledge Query"),
                            ("data_query", "Data Query"),
                            ("report_request", "Report Request"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("accounting_standards", "Accounting Standards"),
                            ("auditing_assurance", "Auditing & Assurance Standards"),
                            ("corporate_laws", "Corporate Laws & Governance"),
                            ("direct_taxes", "Direct Taxes"),
                            ("gst_indirect_taxes", "GST & Indirect Taxes"),
                            (
                                "expert_advisory",
                                "Expert Advisory & Professional Guidance",
                            ),
                            ("members_student_services", "Members & Student Services"),
                            (
                                "sustainability_reporting",
                                "Sustainability Reporting Standards",
                            ),
                            ("acts_regulations", "Acts & Regulations"),
                            (
                                "internal_audit",
                                "Internal Audit & Management Accounting",
                            ),
                            ("digital_accounting", "Digital Accounting & Assurance"),
                            ("ethical_standards", "Ethical Standards"),
                            (
                                "financial_reporting_review",
                                "Financial Reporting Review",
                            ),
                            ("insolvency_valuation", "Insolvency & Valuation"),
                            ("peer_review", "Peer Review"),
                            ("icai_journal", "ICAI e-Journal Knowledge"),
                            ("business_data", "Business Data Query"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=30,
                    ),
                ),
                ("model_used", models.CharField(blank=True, max_length=50)),
                ("tokens_used", models.PositiveIntegerField(default=0)),
                ("processing_time", models.FloatField(blank=True, null=True)),
                (
                    "query_result",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Raw DB query result for data queries",
                    ),
                ),
                (
                    "has_data",
                    models.BooleanField(
                        default=False,
                        help_text="True if response includes business data",
                    ),
                ),
                ("is_helpful", models.BooleanField(blank=True, null=True)),
                ("feedback_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="ai_chatbot.chatsession",
                    ),
                ),
            ],
            options={
                "db_table": "chat_messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="SavedChatResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_by",
                        to="ai_chatbot.chatmessage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "saved_chat_responses",
                "ordering": ["-created_at"],
                "unique_together": {("user", "message")},
            },
        ),
        migrations.CreateModel(
            name="ChatbotUsageStats",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("total_messages", models.PositiveIntegerField(default=0)),
                ("knowledge_queries", models.PositiveIntegerField(default=0)),
                ("data_queries", models.PositiveIntegerField(default=0)),
                ("total_tokens", models.PositiveIntegerField(default=0)),
                (
                    "business",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chatbot_usage",
                        to="business.business",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chatbot_usage",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "chatbot_usage_stats",
                "ordering": ["-date"],
                "unique_together": {("user", "business", "date")},
            },
        ),
    ]
