# Generated by Django 4.2.11 on 2026-03-07 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("business", "0001_initial"),
        ("ai_chatbot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatbotusagestats",
            name="manage_actions",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="chatbotusagestats",
            name="write_actions",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="action_taken",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="action_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("add_income", "Add Income Entry"),
                    ("add_expense", "Add Expense Entry"),
                    ("grant_access", "Grant Branch Access"),
                    ("revoke_access", "Revoke Branch Access"),
                    ("change_role", "Change Member Role"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="domain",
            field=models.CharField(
                blank=True,
                choices=[
                    ("accounting_standards", "Accounting Standards"),
                    ("auditing_assurance", "Auditing & Assurance Standards"),
                    ("corporate_laws", "Corporate Laws & Governance"),
                    ("direct_taxes", "Direct Taxes"),
                    ("gst_indirect_taxes", "GST & Indirect Taxes"),
                    ("expert_advisory", "Expert Advisory & Professional Guidance"),
                    ("members_student_services", "Members & Student Services"),
                    ("sustainability_reporting", "Sustainability Reporting Standards"),
                    ("acts_regulations", "Acts & Regulations"),
                    ("internal_audit", "Internal Audit & Management Accounting"),
                    ("digital_accounting", "Digital Accounting & Assurance"),
                    ("ethical_standards", "Ethical Standards"),
                    ("financial_reporting_review", "Financial Reporting Review"),
                    ("insolvency_valuation", "Insolvency & Valuation"),
                    ("peer_review", "Peer Review"),
                    ("icai_journal", "ICAI e-Journal Knowledge"),
                    ("business_data", "Business Data Query"),
                    ("business_insights", "Business Insights & Analytics"),
                    ("access_management", "Access & Role Management"),
                    ("general", "General"),
                ],
                default="general",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="intent",
            field=models.CharField(
                blank=True,
                choices=[
                    ("knowledge_query", "Knowledge Query"),
                    ("data_query", "Data Query"),
                    ("write_action", "Write Action"),
                    ("manage_access", "Manage Access"),
                    ("business_insight", "Business Insight"),
                    ("report_request", "Report Request"),
                    ("confirmation", "Confirmation"),
                    ("general", "General"),
                ],
                default="general",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="knowledgebase",
            name="domain",
            field=models.CharField(
                choices=[
                    ("accounting_standards", "Accounting Standards"),
                    ("auditing_assurance", "Auditing & Assurance Standards"),
                    ("corporate_laws", "Corporate Laws & Governance"),
                    ("direct_taxes", "Direct Taxes"),
                    ("gst_indirect_taxes", "GST & Indirect Taxes"),
                    ("expert_advisory", "Expert Advisory & Professional Guidance"),
                    ("members_student_services", "Members & Student Services"),
                    ("sustainability_reporting", "Sustainability Reporting Standards"),
                    ("acts_regulations", "Acts & Regulations"),
                    ("internal_audit", "Internal Audit & Management Accounting"),
                    ("digital_accounting", "Digital Accounting & Assurance"),
                    ("ethical_standards", "Ethical Standards"),
                    ("financial_reporting_review", "Financial Reporting Review"),
                    ("insolvency_valuation", "Insolvency & Valuation"),
                    ("peer_review", "Peer Review"),
                    ("icai_journal", "ICAI e-Journal Knowledge"),
                    ("business_data", "Business Data Query"),
                    ("business_insights", "Business Insights & Analytics"),
                    ("access_management", "Access & Role Management"),
                    ("general", "General"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="PendingAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("add_income", "Add Income Entry"),
                            ("add_expense", "Add Expense Entry"),
                            ("grant_access", "Grant Branch Access"),
                            ("revoke_access", "Revoke Branch Access"),
                            ("change_role", "Change Member Role"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "action_data",
                    models.JSONField(
                        default=dict, help_text="Structured data for the action"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Confirmation"),
                            ("confirmed", "Confirmed & Executed"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("confirmation_message", models.TextField(blank=True)),
                ("result_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Auto-expire if no response in 5 minutes"
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pending_actions",
                        to="business.business",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_actions",
                        to="ai_chatbot.chatsession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pending Action",
                "verbose_name_plural": "Pending Actions",
                "db_table": "chat_pending_actions",
                "ordering": ["-created_at"],
            },
        ),
    ]
