# Generated by Django 4.2.11 on 2026-03-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_chatbot", "0002_chatbotusagestats_manage_actions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="action_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("add_income", "Add Income Entry"),
                    ("add_expense", "Add Expense Entry"),
                    ("edit_entry", "Edit Entry"),
                    ("delete_entry", "Delete Entry"),
                    ("grant_access", "Grant Branch Access"),
                    ("revoke_access", "Revoke Branch Access"),
                    ("change_role", "Change Member Role"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="knowledgebase",
            name="source",
            field=models.CharField(
                blank=True,
                help_text="e.g. ICAI Circular, IND-AS 116, Section 80C",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="pendingaction",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("add_income", "Add Income Entry"),
                    ("add_expense", "Add Expense Entry"),
                    ("edit_entry", "Edit Entry"),
                    ("delete_entry", "Delete Entry"),
                    ("grant_access", "Grant Branch Access"),
                    ("revoke_access", "Revoke Branch Access"),
                    ("change_role", "Change Member Role"),
                ],
                max_length=20,
            ),
        ),
    ]
