# Generated by Django 4.2.11 on 2026-03-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_chatbot", "0003_alter_chatmessage_action_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatbotusagestats",
            name="date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="has_data",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="query_result",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("assistant", "Assistant"),
                    ("system", "System"),
                ],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="knowledgebase",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="knowledgebase",
            name="keywords",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="knowledgebase",
            name="source",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="pendingaction",
            name="action_data",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="pendingaction",
            name="expires_at",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="pendingaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Confirmation"),
                    ("confirmed", "Confirmed & Executed"),
                    ("cancelled", "Cancelled"),
                    ("expired", "Expired"),
                ],
                db_index=True,
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="chatbotusagestats",
            index=models.Index(fields=["user", "-date"], name="idx_usage_user_date"),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["session", "created_at"], name="idx_msg_session_time"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(fields=["is_helpful"], name="idx_msg_helpful"),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["user", "is_active", "-updated_at"],
                name="idx_session_user_active",
            ),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["business", "is_active"], name="idx_session_biz_active"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgebase",
            index=models.Index(
                fields=["domain", "is_active"], name="idx_kb_domain_active"
            ),
        ),
        migrations.AddIndex(
            model_name="pendingaction",
            index=models.Index(
                fields=["session", "status"], name="idx_pending_session_status"
            ),
        ),
        migrations.AddIndex(
            model_name="pendingaction",
            index=models.Index(
                fields=["user", "status", "created_at"], name="idx_pending_user_status"
            ),
        ),
        migrations.AddIndex(
            model_name="savedchatresponse",
            index=models.Index(
                fields=["user", "-created_at"], name="idx_saved_user_time"
            ),
        ),
    ]
