# Generated by Django 4.2.11 on 2026-03-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='locality',
            field=models.CharField(blank=True, help_text='Locality/area within the city — used to distinguish branches in the same city', max_length=100),
        ),
        migrations.AlterField(
            model_name='branch',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['business', 'city'], name='branches_busines_c90522_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['business', 'is_active'], name='branches_busines_1f8734_idx'),
        ),
    ]
