# Generated by Django 4.2.11 on 2026-03-07 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("business", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ITRRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "form_type",
                    models.CharField(
                        choices=[
                            ("ITR-1", "ITR-1 (Sahaj)"),
                            ("ITR-2", "ITR-2"),
                            ("ITR-3", "ITR-3"),
                            ("ITR-4", "ITR-4 (Sugam)"),
                            ("ITR-5", "ITR-5"),
                            ("ITR-6", "ITR-6"),
                            ("ITR-7", "ITR-7"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "assessment_year",
                    models.CharField(
                        choices=[
                            ("2021-22", "AY 2021-22"),
                            ("2022-23", "AY 2022-23"),
                            ("2023-24", "AY 2023-24"),
                            ("2024-25", "AY 2024-25"),
                            ("2025-26", "AY 2025-26"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "financial_year",
                    models.CharField(
                        blank=True, help_text="e.g. 2024-25", max_length=10
                    ),
                ),
                ("pan", models.CharField(blank=True, max_length=10)),
                ("taxpayer_name", models.CharField(blank=True, max_length=255)),
                ("file", models.FileField(upload_to="itr/%Y/%m/")),
                ("file_name", models.CharField(max_length=255)),
                ("file_size", models.PositiveBigIntegerField(default=0)),
                ("file_type", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("reviewed", "Reviewed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("celery_task_id", models.CharField(blank=True, max_length=255)),
                ("error_message", models.TextField(blank=True)),
                (
                    "processing_time",
                    models.FloatField(
                        blank=True, help_text="Processing time in seconds", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itr_records",
                        to="business.business",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_itrs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "ITR Record",
                "verbose_name_plural": "ITR Records",
                "db_table": "itr_records",
                "ordering": ["-created_at"],
                "unique_together": {("business", "assessment_year", "form_type")},
            },
        ),
        migrations.CreateModel(
            name="ITRQuery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField(blank=True)),
                ("is_answered", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("answered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "asked_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="itr_queries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "itr_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queries",
                        to="itr_analysis.itrrecord",
                    ),
                ),
            ],
            options={
                "db_table": "itr_queries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ITRComparison",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("comparison_data", models.JSONField(blank=True, default=dict)),
                ("ai_summary", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itr_comparisons",
                        to="business.business",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="itr_comparisons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "itr_record_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparisons_as_first",
                        to="itr_analysis.itrrecord",
                    ),
                ),
                (
                    "itr_record_2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparisons_as_second",
                        to="itr_analysis.itrrecord",
                    ),
                ),
            ],
            options={
                "db_table": "itr_comparisons",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ITRAnalysisResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "gross_total_income",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_deductions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "taxable_income",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "tax_payable",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "tax_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "refund_due",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "tds_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "advance_tax",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "salary_income",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "business_income",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "capital_gains",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "other_income",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "house_property_income",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("ai_summary", models.TextField(blank=True)),
                ("ai_insights", models.JSONField(blank=True, default=list)),
                ("ai_recommendations", models.JSONField(blank=True, default=list)),
                ("tax_saving_tips", models.JSONField(blank=True, default=list)),
                ("risk_flags", models.JSONField(blank=True, default=list)),
                (
                    "raw_extracted_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Complete raw data extracted from ITR document",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "itr_record",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to="itr_analysis.itrrecord",
                    ),
                ),
            ],
            options={
                "db_table": "itr_analysis_results",
            },
        ),
    ]
