# Generated by Django 4.2.11 on 2026-03-02 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Business",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("legal_name", models.CharField(blank=True, max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("retail", "Retail"),
                            ("wholesale", "Wholesale"),
                            ("manufacturing", "Manufacturing"),
                            ("service", "Service"),
                            ("food_beverage", "Food & Beverage"),
                            ("healthcare", "Healthcare"),
                            ("education", "Education"),
                            ("real_estate", "Real Estate"),
                            ("logistics", "Logistics"),
                            ("it_technology", "IT & Technology"),
                            ("finance", "Finance"),
                            ("construction", "Construction"),
                            ("agriculture", "Agriculture"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "gstin",
                    models.CharField(blank=True, max_length=15, null=True, unique=True),
                ),
                (
                    "pan",
                    models.CharField(blank=True, max_length=10, null=True, unique=True),
                ),
                ("registration_no", models.CharField(blank=True, max_length=50)),
                ("tan", models.CharField(blank=True, max_length=10)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=15)),
                ("website", models.URLField(blank=True)),
                ("address_line1", models.CharField(blank=True, max_length=255)),
                ("address_line2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("pincode", models.CharField(blank=True, max_length=10)),
                ("country", models.CharField(default="India", max_length=100)),
                (
                    "financial_year_start",
                    models.PositiveSmallIntegerField(
                        default=4,
                        help_text="Month number when financial year starts (default: 4 = April)",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="business/logos/"
                    ),
                ),
                ("brand_color", models.CharField(default="#6366f1", max_length=7)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("suspended", "Suspended"),
                            ("pending", "Pending Verification"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        limit_choices_to={"role": "business_owner"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="businesses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Business",
                "verbose_name_plural": "Businesses",
                "db_table": "businesses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BusinessSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("enable_cashbook", models.BooleanField(default=True)),
                ("enable_documents", models.BooleanField(default=True)),
                ("enable_itr", models.BooleanField(default=True)),
                ("enable_ai_chatbot", models.BooleanField(default=True)),
                ("notify_on_entry", models.BooleanField(default=True)),
                ("notify_on_document", models.BooleanField(default=True)),
                ("currency", models.CharField(default="INR", max_length=5)),
                ("currency_symbol", models.CharField(default="₹", max_length=5)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="business.business",
                    ),
                ),
            ],
            options={
                "db_table": "business_settings",
            },
        ),
        migrations.CreateModel(
            name="BusinessMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("invited", "Invited"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="business.business",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "business_members",
                "ordering": ["-joined_at"],
                "unique_together": {("business", "user")},
            },
        ),
    ]
