# Generated by Django 4.2.11 on 2026-03-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessmember",
            name="role",
            field=models.CharField(
                choices=[
                    ("business_owner", "Business Owner"),
                    ("branch_manager", "Branch Manager"),
                    ("accountant", "Accountant"),
                    ("staff", "Staff"),
                    ("ca", "CA / Consultant"),
                ],
                db_index=True,
                default="staff",
                max_length=20,
            ),
        ),
    ]
